config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'home', to: 'pages#home'
  
 
 # get '/recipes', to: 'recipes#index'
 # get '/recipes/new', to: 'recipes#new', as: 'new_recipe'
 # post '/recipes', to: 'recipes#create' #handle the form of new recipe by create function
 # get '/recipes/:id/edit', to: 'recipe#edit', as: 'edit_recipe'
 # patch '/recipes/:id', to: 'recipes#update' #update will handle edit recipe form request
 # get 'recipes/id' , to: 'recipes#show', as: 'recipe'
 # delete '/recipes/:id', to: 'recipes#destroy' #for deleting the recipe
 
 
  #rails magic, all the above routes is defined in resources :recipes
  resources :recipes do 
      member do
          post 'like'
      end
  end
  
  
  resources :chefs, except: [:new, :destroy]
  
  get '/register', to: 'chefs#new'  
  
  
  get '/login', to: "logins#new"
  post '/login', to: "logins#create"
  get '/logout', to: "logins#destroy"
  
  
  resources :styles, only: [:new, :create, :show]
  resources :ingredients, only: [:new, :create, :show]        
    
end

app/views/pages/home.html.erb
<div class = "center jumbotron">
  <h1> RECIPE WORLD</h1>
  
  <h2>Join . Share . Learn </h2>
  
  <%= link_to "Sign Up now!", register_path, class:"btn btn-lg btn-success"%>
  
</div>


<div class = "row">
  <div class = "col-lg-8">
    <h3 class = "midrow"> View Receipe as Guest User </h3>
    
    <h2 class = "left"> Browse and view receipies as guest and sign up later </h2>
    
    <P> <%= link_to "Browse Receipe Listings", recipes_path, class:"btn btn-warning btn-small" %></P>
  </div>
  
  <div class = "col-lg-4">
    <h3 class = "midrow"> Sign In to your Account </h3>
    
    <h2 class = "left"> Add/Update recipe, create,review, like, dislike recipes etc. </h2>
    
    <P> <%= link_to "Log in your account", login_path, class:"btn btn-warning btn-small" %></P>
  </div>
  
  
</div>